server:
  servlet:
    context-path: /medium
    session:
      tracking-modes: cookie
  tomcat:
    max-http-post-size: 104857600
    uri-encoding: UTF-8
    additional-tld-skip-patterns: xercesImpl.jar,xml-apis.jar,serializer.jar
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: dev

  jmx:
    default-domain: GpowerBase1
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    basename: i18n/messages
    encoding: UTF-8
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  aop:
    auto: true
    proxy-target-class: true

mybatis-plus:
#指明mapper.xml扫描位置(classpath* 代表编译后类文件根目录)
  mapper-locations: classpath*:mapper/**/*.xml

   #指明实体扫描(多个package用逗号或者分号分隔)
  type-aliases-package: com.gpower.*.entity
  global-config:
    db-column-underline: true
  configuration:
    mapUnderscoreToCamelCase: true

gpower:
  errordetect:
    state: true
    source: beida
    url: http://cloud1.sjytech.com/error_detect/err/detect
  filter:
    xss:
      excludedUris: /login,/favicon.ico,/resource/*,/error/*,/page
  database:
    type: mysql
    cache:
      prefix: GpowerMybatisCache
  session:
    expire: 30
    cache:
      prefix: GpowerSessionCache
  app:
    cache:
      prefix: GpowerAppCache
  shiro:
    auth:
      class: com.gpower.common.auth.MyAuth

#开启尝试登陆次数限制
shiro:
  retryLimit: true




keycloak:
  enabled: false
  #enabled: false
  realm: gpower
  ssl-required: none
  auth-server-url: http://192.168.2.162:8080/auth
  resource: medium
  verify-token-audience: true
  credentials:
    secret: 20c70413-6e5f-4875-b6ad-049105cf530c
  use-resource-role-mappings: true
  confidential-port: 0
  security-constraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: /*

